= Investing-cli

The simple terminal application for tracking financial assets. It can monitor profits from a portfolio. +
Motivation for making this application was to try the new java features (java 16), graalVM and https://gitlab.com/ongresinc/fluent-process[fluent process] and the framework https://github.com/remkop/picocli[picocli]. +
The program supports cryptocurrencies and stock market assets YahooFinanceAPI (some Crypto - Crypto trade data are not accessible).
Currently, it runs only in GNU/Linux distributions. It requires `mpv` nad `notiy-send` commands.
https://www.yahoofinanceapi.com/[YahooFinanceAPI] requires API key. You need run app with the `-k` flag.

=== Features:
- tracking financial assets
- creating a portfolio with holdings
- calculating profit
- adding alerts
- support cryptocurrency and GPW

In the future it will be possible to change the provider:
- Coinbase APi
- MarketStack
- https://www.biznesradar.pl/[Biznes Radar] - scraper for GPW - Polish stock exchange

=== How to use
In the first place you have to make configuration file `portfolio.json` or `portfolio.yaml` in `$HOME` or `XDG_CONFIG_HOME` folder.


.Example for portfolio.yaml file
[source,yaml]
----
- assetName: CIECH
assetSymbol: CIE
type: GPW
holdings:
- buyPrice: 44
amount: 32
alerts:
- price: 60
alertCondition: ABOVE
- price: 52
alertCondition: ABOVE
----

.Example for portfolio.json file
[source,json]
----
[
	{
		"assetName": "CIECH",
		"assetSymbol": "CIE" ,
		"type": "GPW",
		"holdings" : [
			{ 
				"buyPrice" : 44,
				"amount": 32
			},
			{ 
				"sellPrice" : 64,
				"amount": 88
			}
		],
		"alerts" : [
			{ "price" : 52 ,
				"alertCondition": "ABOVE"
			},
			{ "price" : 40 ,
				"alertCondition": "BELOW"
			}
		]
	}
]
----

**Parameters** +

- type - asset type `GPW`, `CRYPTO` or `CC` (crypto-crypto)
- assetName - your name for asset
- assetSymbol - currency or asset symbol, it has to be the sam like in yahoo API
- holdings - put `buyPrice` or `sellPrice` depends on of the investing type and how much did you invested
- alerts - the price level when alert will be active. It takes one of the `alertCondition` - `BELOW` or `ABOVE`

==== Available commands

----
Usage: investing cli [-ahlnpvV] [--[no-]errors] [-c=<portfolioFile>]
                     [-e=<exchangeCurrency>] [-k=<accessKey>]
                     [-o=<onlyAssetsOption>] [-s=<soundAlert>] [-t=<typeOption>]
Your investing portfolio.
Make configuration file `portfolio.json` or `portfolio.yaml` in `$HOME` or
`XDG_CONFIG_HOME` folder.

  -a, --alert                Check out alerts. With the --sound option it will
                               play sound
  -c, --configuration=<portfolioFile>
                             The file with the assets that you want to trace or
                               you own. Provide file or put it in one of the
                               folders: - $HOME/portfolio
                             - investing/portfolio
  -e, --exchange-currency=<exchangeCurrency>
                             Exchange currency for cryptocurrency currency pair.
  -h, --help                 Show this help message and exit.
  -k, --key=<accessKey>      Private access key.
                             Get it from https://www.yahoofinanceapi.com/
  -l, --one-line             Prints short output in one line. Good for showing
                               information on a status bar.
  -n, --notify               Shows notification in dunst.
      --[no-]errors          Doesn't print errors in the output
  -o, --only=<onlyAssetsOption>
                             Process only for specific assets. Provide list of
                               the assets symbol separated by comma
  -p, --portfolio            Shows profits from your portfolio. If sell or buy
                               price are not provided in the config file it
                               will calculate revenue.
                             Remember to change --exchange-currency in order to
                               have the same currency in all markets.
                             Program supports json and yaml formats.

  -s, --sound=<soundAlert>   Audio file for the sound alerts. It requires
                               ffmpeg.
  -t, --type=<typeOption>    Process only for specific assets. Accepts: CRYPTO,
                               GPW, STOCK, CC (crypto crypto)
  -v, --verbose              Shows verbose output.
  -V, --version              Print version information and exit.
----

=== Installation

In order to build a native-image you need to have current GraalVM and prepare local environment - https://www.graalvm.org/reference-manual/native-image/[tutorial]. +
Go to the project directory and execute: +
`mvn package`

=== Used technology

- Java 16, graalVM
- jsoup
- https://github.com/remkop/picocli[picocli]
- http://kong.github.io/unirest-java/#responses[unirest java] 
- https://gitlab.com/ongresinc/fluent-process[fluent process]
